### ISSUE TITLE
"Edit This Page" is a link of type file://

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-platform-guide#303]
See it in https://developer.lightbend.com/docs/akka-platform-guide/microservices-tutorial/dev-env.html

![Screenshot 2020-10-15 at 16 40 57](https://user-images.githubusercontent.com/762126/96145337-634a5100-0f05-11eb-9bf4-abe70609bfab.png)

**Comment by ennru** [comment]
What Antora configuration is needed? @rasummer / @rstento

**Comment by rstento** [comment]
@ennru, you set the value in the playbook, the files we have named site.yml and author-mode-site.yml. Here is the doc on the attribute to set,  edit_url: https://docs.antora.org/antora/2.3/playbook/content-edit-url/

My understanding is that you set this for the root directory of the source files in the git repo and Antora will adjust the link to point at the source file of the page you are looking at.

**Comment by ennru** [comment]
The URL gets rendered correctly if I set `url` to the git repository.
When using the local files with `url: ./../` Antora renders the file URL as the docs state. But I can't get the `edit_url` setting to have any effect. (eg. `edit_url: ~` should switch it off altogether)

Setting `CI=true` doesn't have an effect either.

**Comment by ennru** [comment]
@rstento I wasn't able to make this work. Do you have more pointers?

**Comment by rstento** [comment]
@ennru, I also had trouble getting the edit_url: ~ to shut the link off in the past. Maybe we should file an issue? What behavior do you want? Do you want to shut it off altogether, because we can also do that with template.

**Comment by ennru** [comment]
We'd like to have the links to the source files.

**Comment by rstento** [comment]
Is the repo private? I saw that that that can cause a problem.

**Comment by ennru** [comment]
No, this is public. (For a private repo those links are not as useful, indeed.)

**Comment by rstento** [comment]
@ennru, so I had the same problem in the Akka Serverless doc and I fixed it. There we wanted the Edit this page link to only show for the "dev" version which we actually publish at a different URL, but we don't want it to show on prod because it is a commercial product and we don't want anyone contributing to content. I did this:

in my author-mode-site.yml (named dev.yml in our repo) I added the git url:
content:
  sources:
  - url: https://github.com/lightbend/cloudstate-docs.git
    branches: [HEAD]
in the site.yml (named prod.yml in our repo, I was then able to disable the Edit this page link with this:

content:
  edit_url: ~
  sources:
  - url: https://github.com/lightbend/cloudstate-docs.git
    branches: [master]

Hope this helps, I see that you commented out the git url in site.yml, and didn't add it to author-mode-site.yml, so I wasn't exactly sure what behavior you wanted to see or whether this will fix the link issue or not.

**Comment by ennru** [comment]
AFAICS the edit URL works only if `sources url` points to a repository, which makes sense.
I assume there is another setting for how the edit URL is constructed if the `sources url` is a relative path (which is what we do in author mode).

Anyway, the "Edit this page" links are correct now on akka.io/platform-guide (which now uses `site.yml`).
