### ISSUE TITLE
Use tabs for mvn/sbt

### ISSUE THREAD

**Issue by patriknw** [akka/akka-platform-guide#342]
So far we have based the mvn/sbt choice on the language choice.

In the initial dev-env and template pages the user might not have noticed the language choice yet. For those pages I think we should use mvn/sbt tabs.

In later pages we can initially keep it as is because java/scala choice is clear.

Later, when/if introducing gradle we will have to have tabs for the build tool in all places.

**Comment by octonato** [comment]
You scared me. I thought you were suggesting to use tabs instead of spaces when formatting with mvn/sbt. 😱 

Back to business..

How switching languages will affect the tabs switching of the build tool? Also when we have 2 languages and three building tools? 

There are a few other issue with the current language selection that I noticed. For instance: 

* the language selection is not always visible on the page, maybe it should be always visible
* when switching pages, we go back to java. 
* we should be able to link to a page and select the language usine a querystring, eg: `?lang=scala`

Anyway, I will open issues on the theme repo to describe then in detail.

**Comment by patriknw** [comment]
It should remember the choice (in cookie) when swiching pages when it’s deployed with real web server. Doesn’t work from file.

There should be a build preview mode for that (I havn’t tried myself yet)
