### ISSUE TITLE
Use Alpakka Kafka testkit to spin up Kafka for integration tests

### ISSUE THREAD

**Issue by ennru** [akka/akka-platform-guide#38]

**Comment by patriknw** [comment]
I think that is a discussion topic about if we should use testcontainers or not. I wanted to try without it first, because I don't see the value of it compared to always having Kafka and Cassandra up and running on the side (via docker compose).

Starting and stopping Kafka and Cassandra is slow so that is a reason for not using testcontainers.

When running the services locally we should anyway have Kafka and Cassandra running on the side, so nice to use the same (already started) when running tests.

**Comment by bsideup** [comment]
> Starting and stopping Kafka and Cassandra is slow so that is a reason for not using testcontainers.

Have you tried [the reusable mode](https://github.com/testcontainers/testcontainers-java/pull/1781)? It gives you the same speed but removes the need to manually start anything :)

**Comment by ennru** [comment]
Thanks @bsideup,
The Alpakka Kafka testkit uses the reusable mode and work nicely. For running these examples locally we want to use docker-compose anyway, so for now we rely on it when running the tests as well.

**Comment by patriknw** [comment]
Let's avoid additional tooling until we see a problem with current approach.
